version: '3.9'

services:
  php:
    extra_hosts:
      - ${ROOT_DOMAIN}:host-gateway

  php-debug:
    extra_hosts:
      - ${ROOT_DOMAIN}:host-gateway

  php-profile:
    extra_hosts:
      - ${ROOT_DOMAIN}:host-gateway

  nginx:
    networks:
      - 'default'
      - 'traefik'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bitrix74-nginx.loadbalancer.server.port=80'
      - 'traefik.http.routers.bitrix74-nginx.service=bitrix74-nginx'
      - 'traefik.http.routers.bitrix74-nginx.rule=HostRegexp(`${ROOT_DOMAIN}`, `{subdomain:.*}.${ROOT_DOMAIN}`)'
      - 'traefik.http.routers.bitrix74-nginx.priority=50'
    environment:
      FPM_SENDMAIL: /usr/sbin/sendmail -ti -S mailhog:1025

  push-sub:
    networks:
      - 'default'
      - 'traefik'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bitrix74-push-sub.loadbalancer.server.port=3000'
      - 'traefik.http.routers.bitrix74-push-sub.service=bitrix74-push-sub'
      - 'traefik.http.routers.bitrix74-push-sub.rule=Host(`sub.${ROOT_DOMAIN}`)'
      - 'traefik.http.routers.bitrix74-push-sub.priority=100'

  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog:latest
    networks:
      - 'default'
      - 'traefik'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bitrix74-mailhog.loadbalancer.server.port=8025'
      - 'traefik.http.routers.bitrix74-mailhog.service=bitrix74-mailhog'
      - 'traefik.http.routers.bitrix74-mailhog.rule=Host(`mail.${ROOT_DOMAIN}`)'
      - 'traefik.http.routers.bitrix74-mailhog.priority=100'

  mysql:
    ports:
      - '49374:3306'

networks:
  traefik:
    external: true
    name: traefik
